version: "3"
services:
  api:
    container_name: api
    image: mosyne_api
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    env_file: app/.env
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    command: pytest --cov=. --cov-report=term-missing --verbose tests

  db:
    container_name: mosyne_db
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=db

volumes:
  app-db-data:
