version: "3"
services:
  api:
    container_name: api
    image: mosyne_api
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    environment:
      - TESTING=True
      - DEBUG_MODE=True
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mosyne
      - POSTGRES_PORT=5432
      - POSTGRES_SERVER=db
      - SECRET_JWT=test_secret
      - SENDGRID_API_KEY
      - EMAIL_SENDER
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    command: >
      bash -c "source prestart.sh
      && pytest --cov=. --cov-report=term-missing --verbose tests"

  db:
    container_name: mosyne_db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=testing
