version: "3"
services:
  api:
    container_name: api
    image: mosyne_api
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    environment:
      - TESTING=True
      - DEBUG_MODE=True
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testing
      - POSTGRES_PORT=5432
      - POSTGRES_SERVER=db
      - SECRET_JWT=test_secret
      - SENDGRID_API_KEY
      - EMAIL_SENDER
      - SENDGRID_API_KEY=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
      - EMAIL_SENDER=emanuelosva@gmail.com
    ports:
      - 8080:80
    command: >
      bash -c "rm -rf migrations
      && source prestart.sh
      && pytest --cov=. --cov-report=term-missing --verbose tests"

  db:
    container_name: mosyne_db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=testing
