version: "3"
services:
  api:
    container_name: api
    image: mosyne_api
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    environment:
      - TESTING=True
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testing
      - POSTGRES_PORT=5432
      - POSTGRES_SERVER=db
      - DEBUG_MODE=True
      - SECRET_JWT=test_secret
      - SENDGRID_API_KEY
      - EMAIL_SENDER
    ports:
      - 8080:80
    command: >
      bash -c "rm -rf migrations
      && rm -rf aerich.ini
      && sleep 10s
      && source prestart.sh
      && tail -f /dev/null"

  db:
    container_name: mosyne_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testing
      - POSTGRES_PORT=5432
      - POSTGRES_SERVER=db
