name: mosineAPI
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESING: true
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY_TEST }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER_TEST }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Migrations
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Wait until setup complete
        run: sleep 15s
      - name: Tests
        run: docker exec api pytest --verbose tests
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}
      - name: Deploy to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json

          # Choose current project
          gcloud config set project ${{ secrets.PROJECT_ID }}

          # Deploy project
          gcloud -q app deploy app.yaml --promote
