name: mosineAPI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mosyne
      POSTGRES_PORT: 5432
      POSTGRES_SERVER: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
    needs: test
    steps:
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          serivce_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}
      - name: Deploy to Google App Engine
        run: |
          gcloud auth active-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json

          # Choose current project
          gcloud config set project ${{ secrets.PROJECT_ID }}

          # Deploy project
          gcloud -q app deploy app.yaml --promote
